### ISSUE TITLE
this.mods method overrides mods from this.__base

### ISSUE THREAD

**Issue by cherninely** [sbmaxx/bem-priv#11]

**Comment by DimitryDushkin** [comment]
Есть метод .mod(), т.е. можно выставлять по одному моду без удаления остальных.

**Comment by cherninely** [comment]
Это то можно. Но метод this.mods перезаписываешь этот же метод из this.__base. Так не должно быть :)

**Comment by sbmaxx** [comment]
Если делать extend, то не будет возможности сбросить модификаторы из родительского блока.

**Comment by cherninely** [comment]
можно будет через prop ведь не  ?

**Comment by sbmaxx** [comment]
Прямо сейчас можно просто написать `this.mods(extends(this.mods(), { .. } )`.
