### ISSUE TITLE
Choose API for blocks with mods creation/constructors.

### ISSUE THREAD

**Issue by sbmaxx** [sbmaxx/bem-priv#13]
Declarations are easy

``` js
BEMPRIV.decl({ block: 'block', modName: 'mod', modValue: 'value' };
```

But what about creation? We have at least two popular approachs to create block:

``` js
BEMPRIV.create('block');
BEMPRIV.json('block'); // alias for BEMPRIV.create('block').bemjson();
```

The default `__constructor` accept two parameters `data, params`.

We have to choose new API for `__constructor` and `BEMPRIV.create`.

**Comment by sbmaxx** [comment]
Trying this one

``` js
BEMPRIV.create('block', data, params)
```

Where `params` can contain mods object, for example: `var params = { mods: { foo: 'bar', a: 'b' }  };`

**Comment by cherninely** [comment]
i think would be great use kind of this sintax;

```
BEMPRIV.create({
 block: 'block',
 modName: 'name',
 modValue: 'value'
}, data, params);
```

And in ur create u can check by this way:

```
if (block.block){
//''
} else {
  return new blocks[block](data, params);
}
```

**Comment by sbmaxx** [comment]
``` js
BEMPRIV.create({
 block: 'block',
 modName: 'name',
 modValue: 'value'
}, data, params);
```

``` js
BEMPRIV.create('block', data, { mods: { name: 'value' } }
```

**Comment by cherninely** [comment]
When u set mods inside params variable it looks strange, cause mods - they are about block inheritance, and params - they are about inside logic.
And mods should not be visible in the init() function. It should be incapsulated inside bempriv. imho

**Comment by sbmaxx** [comment]
Mods is not about inheritance, it's literally about "modification". They dynamically modify the block's logic depends on the current modifiers and also modify bemjson.

Here is the difference between pure inheritance and mods.

``` js
BEMPRIV.decl('block', {
    foo: function() { return 'baz' };
});
BEMPRIV.decl({ block: 'another-block', baseBlock: 'block' });
var b = BEMPRIV.create('another-block');
b.foo(); // baz
BEMPRIV.decl({ block: 'block', modName: 'foo', modVal: 'bar' }, {
   foo: function() { return 'bar' };
});
var b = BEMPRIV.create('block');
b.foo(); // baz
b.bemjson(); // { block: 'block' }
b.mod('foo', 'bar');
b.foo(); // bar
b.bemjson(); // { block: 'block', mods: { foo: 'bar' } }
var b = BEMPRIV.create('block', null, { mods: { fo: 'bar' } }
b.foo(); // bar
b.bemjson(); // { block: 'block', mods: { foo: 'bar' } }
```

From the BEM methodology the purpose of mods — to modify block behavior or appearance. In `i-bem.js` it's done via inheritance from block without modifiers.

`params` object is a good way to pass any options, mods or any other bemjson, for example, we can later add possibility to define content like this:

``` js
var content = [];
for(var i = 0; i < 10; i++) {
    content.push(BEMPRIV.create('block', data, { mods: { even: i % 2 == 0 ? 'yes' : 'no', content: 'i = ' + i } }))
}
```

It's should be read as alias for:

``` js
var content = [];
var b;
for(var i = 0; i < 10; i++) {
    b = BEMPRIV.create('block', 'data');
    b.mod(event, i % 2 == 0 ? 'yes' : 'no');
    b.content('i = ' + i);
    content.push(b);
}
```

Output will be the same.

**Comment by sbmaxx** [comment]
Added new API to use like this

``` js
BEMPRIV.create({ block: 'block', mods: { a: 'a' } });
```

Old code also working.

**Comment by DimitryDushkin** [comment]
Cool)
