### ISSUE TITLE
Добавление параметров js, mods, content и т.д.

### ISSUE THREAD

**Issue by DimitryDushkin** [sbmaxx/bem-priv#14]
Например, если надо добавить какое-то свойтво в mods, то надо писать так:

``` js
this.mods(_.assign(this.mods, { newProp: value });
```

Хорошо бы какой-нибудь хелпер для таких ситуаций, ну или прокачать `mods()`, чтобы он понимал, что надо расширить объект, а не заменять его.

**Comment by cherninely** [comment]
Дима :)))
https://github.com/sbmaxx/bem-priv/issues/11

**Comment by DimitryDushkin** [comment]
Илья)) Если бы можно было бы по одному выставлять, уже было бы хорошо.

**Comment by cherninely** [comment]
я то вообще за :) Думаю Рома ответит что то типа "я принимаю пулреквесты" :D

**Comment by DimitryDushkin** [comment]
Надо еще учесть, что `js` может быть `true`, в этом случае надо создавать объект.

**Comment by DimitryDushkin** [comment]
Ок, тогда ждём "за" Ромы и я пулл реквестну.

**Comment by sbmaxx** [comment]
@DimitryDushkin а что не так с `this.mod`? Как раз для проставления одного модификатора. Я не очень понял идею ;)

**Comment by DimitryDushkin** [comment]
@sbmaxx mod правильно работает, да. Хочется, чтобы так работали js() и content().

**Comment by sbmaxx** [comment]
а как ты себе это представляешь с content'ом? который может быть любым типом данных?

**Comment by DimitryDushkin** [comment]
Да, с content(), похоже, никак. Ну тогда только js()?
