### ISSUE TITLE
How include this is tech to bem-project? (ENB)

### ISSUE THREAD

**Issue by belozer** [sbmaxx/bem-priv#21]

**Comment by sbmaxx** [comment]
Just add `bower_components/bem-priv/build/blocks` as new level

**Comment by DimitryDushkin** [comment]
Hello!

It depends on your back-end infrastructure. The most easiest way is to use it as node.js module via `require('bempriv')`

**Comment by sbmaxx** [comment]
Если что, можно уточнить по-русски вопрос. Мы его понимаем

**Comment by belozer** [comment]
Я не до конца понимаю bemtree/bem-priv, но понимаю назначение.

В общем 2 вопроса :)
1. Что нужно сделать для того, чтобы подключить `bem-priv` в bem-stub
2. Как должны выглядеть данные перед пропусканием их через `bem-priv`? Простой алгоритм типа: "Вот есть такой JSON. Мы делаем это и это. Получаем вот это."

**Comment by sbmaxx** [comment]
Добавить в `bower.json`

``` js
"bem-priv":                     "git://github.com/sbmaxx/bem-priv#0.0.26"
```

Добавить в `.enb/make.js` новый уровень переопределения:

``` js
[
        { path: 'libs/bem-core/common.blocks', check: false },
        { path: 'libs/bem-core/desktop.blocks', check: false },
        { path: 'libs/bem-components/common.blocks', check: false },
        { path: 'libs/bem-components/desktop.blocks', check: false },
        { path: 'libs/bem-components/design/common.blocks', check: false },
        { path: 'libs/bem-components/design/desktop.blocks', check: false },
        { path: 'libs/bem-priv/build/blocks', check: false, platform: 'common' },
        'common.blocks',
        'desktop.blocks'
]
```

**Comment by sbmaxx** [comment]
Переоткрой тикет, если остались вопросы.
