### ISSUE TITLE
Unit-testing stub support

### ISSUE THREAD

**Issue by DimitryDushkin** [sbmaxx/bem-priv#22]
Было бы круто, если этот код работал бы =):

``` js
stubBlock = function(name, fn) {

    var stub;

    beforeEach(function() {
        stub = blocks[name]
            ? sinon.stub(blocks, name, fn)
            : BEMPRIV.stub(name);
    });

    afterEach(function() {
        blocks[name]
            ? stub.restore()
            : BEMPRIV.restore(name);
    });

}
```

ну или типа того. В общем, хорошо бы, если можно было бы стабать BEMPRIV блоки.

**Comment by andre487** [comment]
По опыту могу сказать, что лучше не выносить стабы во внешние хелперы. Как минимум, это мешает использовать sinon.sandbox. 

Лучше подумать, как сделать доступ к прототипу блока легче для синона

**Comment by sbmaxx** [comment]
Кажется, научились стабать всё, что нужно. ;)
